- hosts: all
  become: true
  vars:

  tasks:
    - name: Download Jenkins repository file
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
      become: true

    - name: Import Jenkins-CI key
      shell: rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
      become: true

    - name: Install jenkins
      shell: sudo yum install jenkins -y


    - name:  start serv
      shell: sudo systemctl enable jenkins
                                                                                                                               1,7           Top